prog:main.o init.o text.o start.o option.o credit.o perso.o perso2.o single.o multi.o menu.o fonction.o persoo.o persoo2.o
	gcc main.o init.o text.o start.o option.o credit.o perso.o perso2.o single.o multi.o menu.o fonction.o persoo.o persoo2.o -o prog -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
init.o:init.c
	gcc -c init.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
start.o:start.c
	gcc -c start.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
option.o:option.c
	gcc -c option.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
credit.o:credit.c
	gcc -c credit.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
text.o:text.c
	gcc -c text.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
perso.o:perso.c
	gcc -c perso.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
single.o:single.c
	gcc -c single.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
multi.o:multi.c
	gcc -c multi.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
menu.o:menu.c
	gcc -c menu.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
perso2.o:perso2.c
	gcc -c perso2.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
fonction.o:fonction.c
	gcc -c fonction.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
persoo.o:persoo.c
	gcc -c persoo.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
persoo2.o:persoo2.c
	gcc -c persoo2.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
